### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by gf777** [MoinSebi/gfastats#1]
hi @MoinSebi

sorry to intrude I was looking into a way to reach out to you. I've just realized you have a repo with the same name of a tool we are currently developing as part of the Vertebrate Genomes Project (https://github.com/vgl-hub/gfastats). We are planning to publish this soon. I've seen your repo is older than mine so happy to rename it if you think this could cause confusion. However, it seems like your repo is more like a standalone app part of a larger tool, so maybe the two will not be in conflict.

Please advise, thanks!

Giulio

**Comment by MoinSebi** [comment]
Hey @gf777 

It's not a problem for me. You can keep the name :)

Best, 
Sebastian

**Comment by gf777** [comment]
Alright, wonderful thank you @MoinSebi !
